--- #YAML:1.0
name:               DBIx-bind_param_inline
version:            0.03
abstract:           list variables in bh->prepare method instead of calling th->bind_param
author:
    - David Nicol <davidnico@cpan.org>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    DBI:  1
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.50
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
